grace/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path
from grace import views

app_name = 'grace'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home_view,name='home'),
    path('about/',views.About.as_view(),name='about'),
    path('gallery/',views.Gallery.as_view(),name='gallery'),
    path('charity/',views.Donation.as_view(),name='charity'),
    path('sermon/',views.Sermon.as_view(),name='sermon'),
    path('donate/',views.Donate_view,name='donate'),
    path('track/',views.Track.as_view(),name='track'),
    path('policy/',views.Policy.as_view(),name='policy'),
    path('calendar/',views.Calendar.as_view(),name='calendar'),
    path('contact/', views.contact_view, name='contact'),
    path('event/',views.Events.as_view(),name='event'),
    path('event_gallery/',views.Event_gallery.as_view(),name='event_gallery'),
    path('mission/',views.Mission.as_view(),name='mission'),
    path('live/',views.Live.as_view(),name='live'),
    path('pastors/',views.Pastor.as_view(),name='pastors'),
    path('community/',views.Community.as_view(),name='community'),
]

grace_web/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path
from grace import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('',
         include('grace.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls))
    ]+urlpatterns

grace/models.py
from django.db import models

# Create your models here.
# Developed by Surfa
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from rest_framework import serializers
# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"publish")
)


class Sermon(models.Model):
    title = models.CharField(max_length=200, unique=False)
    date = models.DateTimeField(auto_now=True)
    video_link = models.URLField( max_length=500)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=False)
    
    def __str__(self):
        return self.title


class Church_Sermon(models.Model):
    title = models.CharField(max_length=200, unique=False)
    date = models.DateTimeField(auto_now=True)
    video_link = models.URLField( max_length=500)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=False)
    
    def __str__(self):
        return self.title

class Gallery(models.Model):
    title = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image2 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image3 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image4 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image5 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image6 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    
    def __str__(self):
        return self.title


class Church_Gallery(models.Model):
    title = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    
    def __str__(self):
        return self.title


class Event_Gallery(models.Model):
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title = models.CharField(max_length=200, unique=True)
    image2 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title2 = models.CharField(max_length=200, unique=True)
    image3 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title3 = models.CharField(max_length=200, unique=True)
    image4 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title4 = models.CharField(max_length=200, unique=True)
    image5 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title5 = models.CharField(max_length=200, unique=True)
    image6 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title6 = models.CharField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title


class Church_Event_Gallery(models.Model):
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title = models.CharField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title




class Event(models.Model):
    title = models.CharField(max_length=200, unique=True)
    message = models.TextField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    link = models.URLField( max_length=200)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title


class Church_Event(models.Model):
    title = models.CharField(max_length=200, unique=True)
    message = models.TextField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    link = models.URLField( max_length=200)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Charity(models.Model):
    name = models.CharField(max_length=200, unique=True)
    phone = models.CharField(max_length=200, unique=True)
    email = models.CharField(max_length=200, unique=True)
    amount = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name

class Pastors(models.Model):
    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    position = models.CharField(max_length=200, unique=True)
    fb_account = models.CharField(max_length=200, unique=True)
    twitter_account = models.CharField(max_length=200, unique=True)
    ig_account = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=200, unique=True)
    email = models.CharField(max_length=200, unique=True)
    message = models.TextField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name

User = get_user_model()

class Church_Pastors(models.Model):
    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    position = models.CharField(max_length=200, unique=True)
    fb_account = models.CharField(max_length=200, unique=True)
    twitter_account = models.CharField(max_length=200, unique=True)
    ig_account = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name




class Podcasts(models.Model):
    audio_file = models.FileField(upload_to='audio/%Y/%m/%d/', null=True, blank=True)
    audio_image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title = models.CharField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    

class Church_Podcasts(models.Model):
    audio_file = models.FileField(upload_to='audio/%Y/%m/%d/', null=True, blank=True)
    audio_image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title = models.CharField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title


class Sermon_main(models.Model):
    title = models.CharField(max_length=200, unique=False)
    date = models.DateTimeField(auto_now=True)
    video_link = models.URLField( max_length=500)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=False)
    
    def __str__(self):
        return self.title


class Gallery_main(models.Model):
    title = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image2 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image3 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image4 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image5 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image6 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    
    def __str__(self):
        return self.title



class Event_Gallery_main(models.Model):
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title = models.CharField(max_length=200, unique=True)
    image2 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title2 = models.CharField(max_length=200, unique=True)
    image3 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title3 = models.CharField(max_length=200, unique=True)
    image4 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title4 = models.CharField(max_length=200, unique=True)
    image5 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title5 = models.CharField(max_length=200, unique=True)
    image6 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title6 = models.CharField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title



class Event_main(models.Model):
    title = models.CharField(max_length=200, unique=True)
    message = models.TextField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    link = models.URLField( max_length=200)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title



class Pastors_main(models.Model):
    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    position = models.CharField(max_length=200, unique=True)
    fb_account = models.CharField(max_length=200, unique=True)
    twitter_account = models.CharField(max_length=200, unique=True)
    ig_account = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name




class Podcasts_main(models.Model):
    audio_file = models.FileField(upload_to='audio/%Y/%m/%d/', null=True, blank=True)
    audio_image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    title = models.CharField(max_length=200, unique=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

grace/forms.py
# Developed by Surfa
from django import forms
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Contact, Charity



# class ImageForm(forms.ModelForm):
#     """Form for the image model"""
#     class Meta:
#         model = Galary
#         fields = ('title', 'image2')
class CharityForm(forms.ModelForm):
    
    class Meta:
        model = Charity
        fields = ('name','phone','email','amount')
    
    Widgets  = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'phone': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.TextInput(attrs={'class': 'form-control'}),
        'amount': forms.TextInput(attrs={'class': 'form-control'}),
    }


class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        fields = ('name','email','message')
    
    Widgets  = {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.TextInput(attrs={'class': 'form-control'}),
        'message': forms.TextInput(attrs={'class': 'form-control'}),
    }

grace/views.py
from django.shortcuts import render
from django.views import generic
from telnetlib import GA
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.views import generic
from .models import Church_Gallery, Church_Sermon , Church_Event , Charity , Church_Pastors, Church_Event_Gallery, Church_Podcasts
from .forms import ContactForm, CharityForm
from django.views.generic.edit import FormView
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib import messages
from .convert_audio_file import convert_to_mp3
from rest_framework.generics import (UpdateAPIView)
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from rest_framework.parsers import MultiPartParser


# Create your views here.

# class Home(generic.ListView):
#     queryset = Charity.objects.all()
#     template_name = 'grace/index.html'


class Sermonn(generic.TemplateView):
    
    template_name = 'grace/m-index.html'



class Give(generic.TemplateView):
    template_name = 'grace/give.html'


class Sermon(generic.ListView):
    queryset = Church_Sermon.objects.all()
    template_name = 'grace/sermon.html'

class Policy(generic.TemplateView):
    template_name = 'novel/policy.html'

class Live(generic.TemplateView):
    #queryset = Gallery.objects.all()
    template_name = 'grace/live.html'



# class Bod(generic.ListView):
#     queryset = Bod.objects.all()
#     template_name = 'novel/team.html'

class Community(generic.TemplateView):
    template_name = 'grace/community.html'

class Gallery(generic.ListView):
    queryset = Church_Gallery.objects.all()
    template_name = 'grace/gallery.html'


class Events(generic.ListView):
    queryset = Church_Event.objects.all()
    template_name = 'grace/events.html'


class Calendar(generic.TemplateView):
    template_name = 'grace/calendar.html'


class Event_gallery(generic.ListView):
    queryset = Church_Event_Gallery.objects.all()
    template_name = 'grace/gallery2.html'


class Pastor(generic.ListView):
    queryset = Church_Pastors.objects.all()
    template_name = 'grace/team.html'


class Mission(generic.TemplateView):
    template_name = 'grace/mission.html'


class Donation(generic.TemplateView):
    template_name = 'grace/donation.html'

class Track(generic.ListView):
    queryset = Church_Podcasts.objects.all()
    template_name  = 'grace/podcast.html'





class About(generic.TemplateView):
    template_name = 'grace/about.html'
    


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contact request submitted successfully.')
            return render(request, 'grace/contact.html', {'form': ContactForm(request.GET)})
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)
    form = ContactForm()
    context = {'form': form}
    return render(request, 'grace/contact.html', context)

def Home_view(request):
    if request.method == 'POST':
        form = CharityForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Donation request submitted successfully.')
            return render(request, 'grace/index.html', {'form': CharityForm(request.GET)})
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)
    form = CharityForm()
    context = {'form': form}
    return render(request, 'grace/index.html', context)


def Donate_view(request):
    if request.method == 'POST':
        form = CharityForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Donation request submitted successfully.')
            return render(request, 'grace/donate.html', {'form': CharityForm(request.GET)})
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)
    form = CharityForm()
    context = {'form': form}
    return render(request, 'grace/donate.html', context)

# def Audio_store(request):
#     if request.method == 'POST':
#         form = AudioForm(request.POST,request.FILES or None)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Audio  uploaded successfully.')
#             return render(request, 'grace/sermon.html', {'form': ContactForm(request.GET)})
#         else:
#             messages.error(request, 'Invalid form submission.')
#             messages.error(request, form.errors)
#     form = ContactForm()
#     context = {'form': form}
#     return render(request, 'grace/sermon.html', context)

grace/templates/grace/base1.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap5 %}

<head>
    <meta charset="utf-8">
    <title>Grace Mission</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'asset/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'asset/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'asset/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'asset/favicon/site.webmanifest' %}">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'asset/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'asset/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'asset/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'asset/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/audioplayer.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <div class="container-fluid fixed-top px-0 wow fadeIn" data-wow-delay="0.1s">
        <div class="top-bar text-white-50 row gx-0 align-items-center d-none d-lg-flex">
            <div class="col-lg-6 px-5 text-start">
                <small><i class="fa fa-map-marker  me-2"></i>PS Global Gate1, Plot 399, 42nd Street Community 25</small>
                <small class="ms-4"><i class="fa fa-envelope me-2"></i>gracemission.baptist@gmail.com</small>
            </div>
            <div class="col-lg-6 px-5 text-end">
                <small>Follow us:</small>
                <a class="text-danger ms-3" href=""><i class="fab fa-facebook-f"></i></a>
                <a class="text-danger ms-3" href=""><i class="fab fa-twitter"></i></a>
                <a class="text-danger ms-3" href=""><i class="fab fa-linkedin-in"></i></a>
                <a class="text-danger ms-3" href=""><i class="fab fa-instagram"></i></a>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-dark py-lg-0 px-lg-5 wow fadeIn" data-wow-delay="0.1s">
            <a href="{% url 'grace:home' %}" class="navbar-brand ms-4 ms-lg-0"><img src="{% static 'asset/img/glogo.png' %}" alt="">
                <img src="{% static 'asset/img/log2.png' %}" alt="">
                {% comment %} <h1 class="fw-bold text-primary m-0">Grace<span class="text-white">Mission</span></h1> {% endcomment %}
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a href="{% url 'grace:home' %}" class="nav-item nav-link active">Home</a>
                    <a href="/gallery" class="nav-item nav-link">Gallery</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Events</a>
                        <div class="dropdown-menu m-0">
                            <a href="/event" class="dropdown-item">Events</a>
                            <a href="/event_gallery" class="dropdown-item">Events Gallery</a>
                            <a href="/calendar" class="dropdown-item">Events Calendar</a>
                        </div>
                        
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Services</a>
                        <div class="dropdown-menu m-0">
                            <a href="/sermon" class="dropdown-item">Daily Services</a>
                            <a href="/live" class="dropdown-item">Live stream</a>
                            <a href="/track" class="dropdown-item">Podcast</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Our Church</a>
                        <div class="dropdown-menu m-0">
                            <a href="/about" class="dropdown-item">About Our Church</a>
                            <a href="/community" class="dropdown-item">Our Community</a>
                            <a href="/mission" class="dropdown-item">Our Mission</a>
                            <a href="/sermon" class="dropdown-item">Sermons</a>
                            <a href="/track" class="dropdown-item">Podcast</a>
                            <a href="/pastors" class="dropdown-item">Our Pastors</a>
                            <a href="/contact" class="dropdown-item">Contacts</a>
                        </div>
                        
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Charity</a>
                        <div class="dropdown-menu m-0">
                            <a href="/charity" class="dropdown-item">Donate</a>
                        </div>
                        
                    </div>
                    <a href="/contact" class="nav-item nav-link">Contact</a>
                </div>
                <div class="d-none d-lg-flex ms-2">
                    <a class="btn btn-outline-primary py-2 px-3" href="/charity">
                        Donate
                        <div class="d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2">
                            <i class="fa fa-arrow-right"></i>
                        </div>
                    </a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->
    {% block content %}
    {% load static %}
    {% load bootstrap5 %}
    {% endblock content %}

grace/templates/grace/events.html
{% extends 'grace/base1.html' %}
{% block content %}
{% load static %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header2 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center">
            <h1 class="display-4 text-white animated slideInDown mb-4">Events</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                    <li class="breadcrumb-item"><a class="text-white" href="#">Event</a></li>
                    <li class="breadcrumb-item text-primary active" aria-current="events">Events</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
    <!-- About Start -->
        <!-- Causes Start -->
        <div class="container-xxl bg-light my-5 py-5">
            <div class="container py-5">

                <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
                    <div class="d-inline-block rounded-pill bg-secondary text-white py-1 px-3 mb-3">Recent Events</div>
                    <h1 class="display-6 mb-5"> Watch recent event</h1>
                </div>
                <div class="row g-4 justify-content-center">
                    {% for church_event in event_list %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="causes-item d-flex flex-column bg-white border-top border-5 border-primary rounded-top overflow-hidden h-100">
                            <div class="text-center p-4 pt-0">
                                <div class="d-inline-block bg-primary text-white rounded-bottom fs-5 pb-1 px-3 mb-4">
                                    <small>{{ church_event.title }}</small>
                                </div>
                                <h5 class="mb-3">{{ church_event.date }}</h5>
                                <p>{{ church_event.message }}</p>
                            </div>
                            <div class="position-relative mt-auto">
                                <img class="img-fluid" src="{{ church_event.image.url }}" alt="">
                                <div class="causes-overlay">
                                    <a class="btn btn-outline-primary" href="{{ church_event.link }}">
                                        watch
                                        <div class="d-inline-flex btn-sm-square bg-primary text-white rounded-circle ms-2">
                                            <i class="fa fa-arrow-right"></i>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Causes End -->
    </div>
    {% include 'grace/footer1.html' %}
    {% endblock content %}

grace/templates/grace/team.html
{% extends 'grace/base1.html' %}
{% block content %}
{% load static %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header3 mb-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container text-center">
            <h1 class="display-4 text-white animated slideInDown mb-4">Our Pastors</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                    <li class="breadcrumb-item"><a class="text-white" href="#">Our Church</a></li>
                    <li class="breadcrumb-item text-primary active" aria-current="page">Pastors</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->
    <!-- Team Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
                <div class="d-inline-block rounded-pill bg-secondary text-white py-1 px-3 mb-3">Pastors</div>
                <h1 class="display-6 mb-5">Pastors</h1>
            </div>
            <div class="row g-4">
                {% for church_pastors in church_pastors_list %}
                <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="team-item position-relative rounded overflow-hidden">
                        <div class="overflow-hidden">
                            <img class="img-fluid" src="{{ church_pastors.image.url }}" alt="">
                        </div>
                        <div class="team-text bg-light text-center p-4">
                            <h5>{{ church_pastors.name }}</h5>
                            <p class="text-primary">{{ church_pastors.position }}</p>
                            <div class="team-social text-center">
                                <a class="btn btn-square" href="{{ church_pastors.fb_account }}"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-square" href="{{ church_pastors.twitter_account }}"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-square" href="{{ church_pastors.ig_account }}"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Team End -->
    {% include 'grace/footer1.html' %}
    {% endblock content %}